### ISSUE TITLE
Create a plugin version that works with original Grayjay

### ISSUE THREAD

**Issue by netux** [netux/grayjay-source-youtube#5]
From https://github.com/netux/grayjay-source-youtube/pull/2#issuecomment-2041051216

## Idea

Create a version of the plugin that overwrites a video's `.title` and `.thumbnails` directly. It should also have its own source ID, so it can be installed alongside the FUTO's YouTube source.

## TODO

- [ ] Figure out a way to compile two plugins versions from one
  - Possibly set up bundling with [Rollup](https://rollupjs.org/introduction/) or [Vite](https://vitejs.dev/), and install a macros plugin ([like this one?](https://github.com/cawa-93/rollup-plugin-dynamic-macros)) which would allow us to compile certain parts of the source code separately for each version.
- [ ] Use macros to create separate paths for each version
- [ ] Figure out how to set this up with the current branching model (`feature/dearrow` merging into `with-dearrow`)

**Comment by Bluscream** [comment]
It looks like they might have reconsidered your usecase (https://chat.futo.org/#narrow/stream/46-Grayjay/topic/Tasker.20automation/near/114569)

But i don't think they want to spend too much time on it, so you probably will have to do all the legwork.

Did you ever PR your changes to their GrayJay repo on github or gitlab?
Will other sources have to be changed to accommodate your changes? If yes, are you willing to PR these changes to them aswell?

**Comment by netux** [comment]
> I don't think they want to spend too much time on it, so you probably will have to do all the legwork.

I think I already have? All that's left is to make a PR of [`feature/alternative-metadata`](https://github.com/netux/grayjay-android/tree/feature/alternative-metadata) for them I guess.

> Did you ever PR your changes to their GrayJay repo on github or gitlab?

Not yet, no.

Again, one thing that deters me is how long search takes with DeArrow.
Another thing I found might be a problem is how I'm using the DeArrow logo as an universal "alternative metadata toggle" button (because I didn't want to use text), which assumes other extensions that do the same for other sources wouldn't exist.
Also, maybe some people wouldn't like that button to be so prominent.

These aren't really excuses - there should be solutions to all of these - but right now I'm content with my fork.
Maybe I will revisit it in the future (or someone else feels like contributing!)

> Will other sources have to be changed to accommodate your changes? If yes, are you willing to PR these changes to them aswell?

Luckily no, otherwise I would've had to change all other plugins too.

The only changes to the sources API is how videos can now have an optional `alternativeName` and optional thumbnails of type `"alternative"`.

**Comment by netux** [comment]
Done with release [168.2-with-dearrow](https://github.com/netux/grayjay-source-youtube/releases/tag/168.2-with-dearrow)
